src/03 Host/CompanyName.ProjectName.Web.Host/Controllers/SysUserController.cs
#region using

using CompanyName.ProjectName.ICommonServer;
using CompanyName.ProjectName.ICommonServer.Sys;
using CompanyName.ProjectName.Core;
using CompanyName.ProjectName.Web.Host.Framework;
using CompanyName.ProjectName.Web.Host.Model;
using CompanyName.ProjectName.Web.Host.Web.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

#endregion using

namespace CompanyName.ProjectName.Web.Host.Controllers
{
    public class SysUserController : CustomController
    {
        public IUserApp UserApp { get; set; }
        public IRoleApp RoleApp { get; set; }
        public SiteConfig Config;
        public IDepartmentApp DepartmentApp { get; set; }

        public SysUserController(IOptions<SiteConfig> option)
        {
            Config = option.Value;
            DefaultPageSize = ZConvert.StrToInt(Config.Configlist.FirstOrDefault(o => o.Key == "pagesize")?.Values);
        }

        #region Index

        // GET: /<controller>/
        public async Task<IActionResult> Index(UserOption filter, int? page)
        {
            ViewBag.filter = filter;
            var currentPageNum = page ?? 1;
            var result = await UserApp.GetPageAsync(currentPageNum, DefaultPageSize, filter);
            var model = new BaseListViewModel<UserSunpleDto>
            {
                list = result.Data,
                Paging =
                {
                    CurrentPage = currentPageNum,
                    ItemsPerPage = DefaultPageSize,
                    TotalItems = result.ItemCount
                }
            };
            return View(model);
        }

        #endregion Index

        #region Create

        public async Task<IActionResult> Create()
        {
            var model = new UserCreateModel();
            var data = await RoleApp.GetListAsync(new RoleOption { });
            var selects = data.Select(o => new SelectListItem { Value = o.Id.ToString(), Text = o.Name }).ToList();
            model.Rolelist = selects;
            model.GoBackUrl = SetingBackUrl(this.HttpContext.Request);
            var deptdata = await DepartmentApp.GetDepartmentListAsync();
            deptdata = deptdata.SortDepartmentsForTree().ToList();
            var selectList = new List<SelectListItem>();
            foreach (var c in deptdata)
                selectList.Add(new SelectListItem()
                {
                    Value = c.Id.ToString(),
                    Text = c.GetFormattedBreadCrumb(deptdata),
                    Selected = c.Id == model.DepartmentId
                });

            model.deptlist = selectList;
            ViewBag.GoBackUrl = SetingBackUrl(this.HttpContext.Request);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(UserCreateModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(ResultDto.Err("数据验证失败;" + GetErrorFromModelStateStr()));
            }
            var user = model.MapTo<User>();
            user.Password = CompanyName.ProjectName.Core.Security.MD5Encrypt.MD5(user.Password);
            if (!string.IsNullOrWhiteSpace(user.Avatar))
            {
                var saveUrl = IMGOperate.BaseSave(ImagePathType.员工头像, user.Avatar);
                user.Avatar = saveUrl;
            }
            var r = await UserApp.InsertAsync(user, await CurrentUser());
            return Json(r);
        }

        #endregion Create

        #region 删除

        [HttpPost]
        public async Task<IActionResult> Delete(long Id)
        {
            var r = await UserApp.DeleteAsync(Id, 0, await CurrentUser());
            return Json(r);
        }

        /// <summary>
        /// 修改用户登录状态
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Updatestatus(long id)
        {
            var r = await UserApp.Updatestatus(id, await CurrentUser());
            return Json(r);
        }

        #endregion 删除

        #region 修改

        public async Task<IActionResult> Edit(long id)
        {
            UserEditModel model = new UserEditModel();
            User user = await UserApp.GetAsync(id);
            if (user == null)
            {
                return NotFind();
            }
            model = user.MapTo<UserEditModel>();
            model.GoBackUrl = SetingBackUrl(this.HttpContext.Request);
            var data = await RoleApp.GetListAsync(new RoleOption { });
            List<SelectListItem> selects = data.Select(o => new SelectListItem { Value = o.Id.ToString(), Text = o.Name }).ToList();
            model.Rolelist = selects;

            var deptdata = await DepartmentApp.GetDepartmentListAsync();
            deptdata = deptdata.SortDepartmentsForTree().ToList();
            var selectList = new List<SelectListItem>();

            foreach (var c in deptdata)
                selectList.Add(new SelectListItem()
                {
                    Value = c.Id.ToString(),
                    Text = c.GetFormattedBreadCrumb(deptdata),
                    Selected = c.Id == model.DepartmentId
                });

            model.deptlist = selectList;

            ViewBag.GoBackUrl = SetingBackUrl(this.HttpContext.Request);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserEditModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(ResultDto.Err(GetErrorFromModelStateStr()));
            }

            if (!string.IsNullOrWhiteSpace(model.Avatar))
            {
                if (model.Avatar.Contains("["))
                {
                    var saveUrl = IMGOperate.BaseSave(ImagePathType.员工头像, model.Avatar);
                    model.Avatar = saveUrl;
                }
            }

            var m = await UserApp.GetAsync(model.Id);

            if (m == null)
            {
                return Json(ResultDto.Err("数据不存在或已被删除"));
            }

            m = model.MapToMeg<UserEditModel, User>(m);

            var r = await UserApp.UpdateUserInfoAsync(m, await CurrentUser());
            return Json(r);
        }

        #endregion 修改

        #region ChangePassword

        [IgnoreAuthorize]
        public async Task<IActionResult> ChangePassword()
        {
            var r = await CurrentUser();
            ViewBag.RealName = r.RealName;
            return View();
        }

        [HttpPost]
        [IgnoreAuthorize]
        public async Task<IActionResult> ChangePassword(ChangePasswordModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(ResultDto.Err(GetErrorFromModelStateStr()));
            }
            var c = await CurrentUser();
            var r = await UserApp.ChangePasswordAsync(c.Id, model.Password, model.NewPassword, 0, c);

            return Json(r);
        }

        [HttpPost]
        //[IgnoreAuthorize]
        public async Task<IActionResult> ResertPassword(string id)
        {
            var r = await UserApp.ResetPasswordAsync(ZConvert.StrToLong(id), "123456", 0, await CurrentUser());
            return Json(r);
        }

        #endregion ChangePassword
    }
}

src/03 Host/CompanyName.ProjectName.Web.Host/Controllers/WebConfigController.cs
#region using

using CompanyName.ProjectName.ICommonServer;
using CompanyName.ProjectName.ICommonServer.Sys;
using CompanyName.ProjectName.Core;
using CompanyName.ProjectName.Enum;
using CompanyName.ProjectName.Web.Host.Framework;
using CompanyName.ProjectName.Web.Host.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Linq;
using System.Threading.Tasks;

#endregion using

namespace CompanyName.ProjectName.Web.Host.Controllers
{
    public class WebConfigController : CustomController
    {
        public IWebConfigApp WebConfigApp { get; set; }
        public IUserApp UserApp { get; set; }
        public SiteConfig Config;

        public WebConfigController(IOptions<SiteConfig> option)
        {
            Config = option.Value;
            DefaultPageSize = ZConvert.StrToInt(Config.Configlist.FirstOrDefault(o => o.Key == "pagesize")?.Values);
        }

        #region Index

        // GET: /<controller>/
        public async Task<IActionResult> Index(WebConfigOption filter, int? page)
        {
            ViewBag.filter = filter;
            var currentPageNum = page ?? 1;
            filter.RowsPrePage = DefaultPageSize;
            filter.PageNumber = currentPageNum;
            var result = await WebConfigApp.GetPageAsync(filter);
            var model = new BaseListViewModel<WebConfigDto>
            {
                list = result.Data.Data,
                Paging =
                {
                    CurrentPage = currentPageNum,
                    ItemsPerPage = DefaultPageSize,
                    TotalItems = result.Data.ItemCount
                }
            };
            return View(model);
        }

        #endregion Index

        #region Create

        public async Task<IActionResult> Create()
        {
            CreateWebConfigDto model = new CreateWebConfigDto();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateWebConfigDto model)
        {
            if (!ModelState.IsValid)
            {
                return Operation(false, "数据验证失败;" + GetErrorFromModelStateStr(), "");
            }
            var r = await WebConfigApp.CreateAsync(model, await CurrentUser());
            return Json(r);
        }

        #endregion Create

        #region 删除

        [HttpPost]
        public async Task<IActionResult> Delete(long Id)
        {
            var r = await WebConfigApp.DeleteAsync(Id, await CurrentUser());
            return Json(r);
        }

        /// <summary>
        /// 修改用户登录状态
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Updatestatus(long id)
        {
            var r = await UserApp.Updatestatus(id, await CurrentUser());
            return Json(r);
        }

        #endregion 删除

        #region 修改

        public async Task<IActionResult> Edit(long Id)
        {
            var r = await WebConfigApp.GetDetailAsync(Id);
            return r.Code != CodeEnum.Ok ? NotFind() : View(r.Data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UpdateWebConfigDto model)
        {
            if (!ModelState.IsValid)
            {
                return Operation(false, GetErrorFromModelStateStr());
            }
            var r = await WebConfigApp.UpdateAsync(model, await CurrentUser());
            return Json(r);
        }

        #endregion 修改
    }
}

src/03 Host/CompanyName.ProjectName.Web.Host/Views/WebConfig/Create.cshtml
@using  CompanyName.ProjectName.Web.Host.Model
@model CompanyName.ProjectName.ICommonServer.CreateWebConfigDto
@{
    Layout = "_LayoutForm";
    ViewData["title"] = "配置添加";
}

@section headers{

}

<form id="form2">

    @*@Html.HiddenFor(o => o.GoBackUrl)*@

    <div style="padding-top: 0px; margin-right: 30px;">
        <table class="form">
            <tr>
                <th class="formTitle"><span class="field-item-required light-red">*</span>key</th>
                <td class="formValue">
                    @Html.TextBoxFor(model => model.ConfigKey, new { placeholder = "请输入key", @class = "form-control" })
                </td>
                <td>
                    @Html.ValidationMessageFor(o => o.ConfigKey, null, new { @class = "help-inline" })
                </td>
            </tr>

            <tr>
                <th class="formTitle"><span class="field-item-required light-red">*</span>值</th>
                <td class="formValue">
                    @Html.TextBoxFor(model => model.ConfigValue, new { placeholder = "请输入值", @class = "form-control" })
                </td>
                <td>
                    @Html.ValidationMessageFor(o => o.ConfigValue, null, new { @class = "help-inline" })
                </td>
            </tr>

            <tr>
                <th class="formTitle"><span class="field-item-required light-red">*</span>环境</th>
                <td class="formValue">
                    @Html.TextBoxFor(model => model.ConfigType, new { placeholder = "请输入环境", @class = "form-control" })
                </td>
                <td>
                    @Html.ValidationMessageFor(o => o.ConfigType, null, new { @class = "help-inline" })
                </td>
            </tr>

            <tr>
                <th class="formTitle"><span class="field-item-required light-red">*</span>备注</th>
                <td class="formValue">
                    @Html.TextBoxFor(model => model.ConfigDetail, new { placeholder = "请输入备注", @class = "form-control" })
                </td>
                <td>
                    @Html.ValidationMessageFor(o => o.ConfigDetail, null, new { @class = "help-inline" })
                </td>
            </tr>
        </table>
        <div class="clearfix form-actions">
            <label class="col-sm-3 control-label" for="form-field-1"> &nbsp; </label>
            <div class="col-md-9">
                <button class="btn btn-info" type="button" id="btnSave">
                    <i class="ace-icon fa fa-check bigger-110"></i>
                    确定
                </button>
                &nbsp;
                &nbsp;
                &nbsp;
                &nbsp;
                <a href="/WebConfig/index" class="btn"><i class="ace-icon fa fa-arrow-left icon-on-left bigger-110"></i>返回</a>
            </div>
        </div>
    </div>
</form>

@section scripts{
    <script>
        $("#btnSave").click(function (ev) {
            var $form = $("#form2");
            if ($form.valid()) {
                $.ajax({
                    url: "/WebConfig/Create",
                    data: $form.serialize(),
                    type: "POST",
                    cache: false,
                    async: false,
                    beforeSend: function () {
                        $("#btnSave").attr("disabled", "disabled");
                    },
                    success: function (r) {

                        if (r.code == 0) {
                            location.href = "/WebConfig/index?ram=" + Math.random();// r.GoBackUrl;
                        }
                        else  // 其他问题
                        {
                            $.MsgBox.Alert(r.msg);
                        }
                        $("#btnSave").removeAttr("disabled");
                    },
                    error: function () {
                        $.MsgBox.Alert("保存失败");
                        $("#btnSave").removeAttr("disabled");
                    }
                });
            }
            else {
                $("#btnSave").removeAttr("disabled");
            }
        });
    </script>
}

src/03 Host/CompanyName.ProjectName.Web.Host/Views/WebConfig/Index.cshtml
@using cloudscribe.Web.Pagination
@using CompanyName.ProjectName.Web.Host
@using CompanyName.ProjectName.Web.Host.Controllers
@using  CompanyName.ProjectName.ICommonServer
@using CompanyName.ProjectName.Web.Host.Model
@model BaseListViewModel<CompanyName.ProjectName.ICommonServer.WebConfigDto>
@{
    Layout = "_Layoutlist";
    WebConfigOption filer = ViewBag.filter as WebConfigOption;

}

@section headers{

}

@*<section class="content-header">
        <h1>
            管理表格
            <small>bootstrap-table管理表格</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">Simple</li>
        </ol>
    </section>*@
<!-- Main content -->
<section class="content">

    <div class="row">
        <!-- BEGIN SAMPLE TABLE PORTLET-->
        <div class="col-md-12">
            <!-- BEGIN SAMPLE TABLE PORTLET-->
            <div class="box-body" style="padding-bottom:0px;">
                <!--<div class="panel panel-default">-->

                <div class="search row">
                    <div class="col-sm-12 form-group">
                        <div class="form-inline">
                            <form action="/WebConfig/index" method="get" id="searchform">

                                @*<form role="form" asp-controller="SysUser" asp-action="index" method="get" asp-antiforgery="false">*@

                                <div class="form-group ">
                                    <label class="control-label  label-lg label-md">配置Key:</label>
                                    @Html.TextBox("ConfigKey", @filer.ConfigKey, new { placeholder = "配置Key", @class = "form-control input-small input-sm" })
                                </div>

                                <span class="form-group btn-group">
                                    <button class="btn btn-sm btn-info" type="submit"><i class="fa fa-search"></i> 搜索</button>
                                </span>
                            </form>
                        </div>
                    </div>
                </div>
                <!--</div>-->
                <div style="  position: relative;
            margin-top: 10px;
            margin-bottom: 10px;
            line-height: 34px;">
                    <div id="toolbar" class="btn-group">

                        <button id="btn_add" type="button" class="btn btn-default">

                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>新增
                        </button>

                        @*   <button id="btn_delete" type="button" class="btn btn-default">
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>删除
                            </button>*@
                    </div>
                </div>

                <div class="table-scrollable">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr class="heading">
                                <th>Id</th>
                                <th>Key</th>
                                <th>值</th>
                                <th>环境</th>
                                <th>创建人</th>
                                <th>创建时间</th>
                                <th style="width:240px">操作</th>
                            </tr>
                        </thead>
                        <tbody id="tbody">

                            @if (Model.list.Count > 0)
                            {
                                @foreach (var s in Model.list)
                                {
                                    <tr>
                                        <td>@s.Id</td>
                                        <td>@s.ConfigKey</td>
                                        <td>@s.ConfigValue</td>
                                        <td>@s.ConfigType </td>
                                        <td>@s.CreatorUserId</td>

                                        <td>@(s.CreatorTime.ToString("yyyy/MM/dd HH:mm:ss")) </td>

                                        <td>
                                            <a href="javascript:void(0);" onclick="btndelete('@s.Id');" class="aDel">删除</a>

                                            <a href="/WebConfig/Edit?Id=@s.Id">编辑</a>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
                @if (Model.list.Count > 0)
                {
                    <div class="fixed-table-pagination" style="display: block;">
                        @*<div class="pull-left pagination-detail">*@
                        <div class="col-sm-4 hidden-xs" style="padding-top:4px;">

                            <span class="pagination-info"> 显示 第 @((Model.Paging.ItemsPerPage * (Model.Paging.CurrentPage - 1)) + 1) 到 @((Model.Paging.ItemsPerPage * Model.Paging.CurrentPage) > Model.Paging.TotalItems ? Model.Paging.TotalItems : (Model.Paging.ItemsPerPage * Model.Paging.CurrentPage)) 条， 共 @Model.Paging.TotalItems 条</span>
                        </div>
                        <div class="col-sm-8 dataTables_paginate;" style="  padding-right:15px; margin-right:0px;">

                            @*<li class="active"><a href="javascript:void(0)">10</a></li><li><a href="javascript:void(0)">25</a></li><li><a href="javascript:void(0)">50</a></li><li><a href="javascript:void(0)">100</a></li></ul></span> 条记录</span></div><div class="pull-right pagination"><ul class="pagination"><li class="page-pre"><a href="javascript:void(0)">‹</a></li><li class="page-number active"><a href="javascript:void(0)">1</a></li><li class="page-number"><a href="javascript:void(0)">2</a></li><li class="page-number"><a href="javascript:void(0)">3</a></li><li class="page-number"><a href="javascript:void(0)">4</a></li><li class="page-number"><a href="javascript:void(0)">5</a></li><li class="page-last-separator disabled"><a href="javascript:void(0)">...</a></li><li class="page-last"><a href="javascript:void(0)">10</a></li><li class="page-next"><a href="javascript:void(0)">›</a>
                                </li>*@
                            <cs-pager cs-paging-pagesize="@Model.Paging.ItemsPerPage"
                                      cs-paging-pagenumber="@Model.Paging.CurrentPage"
                                      cs-paging-totalitems="@Model.Paging.TotalItems"
                                      cs-pagenumber-param="page"
                                      asp-controller="WebConfig"
                                      asp-action="index"
                                      asp-route-ConfigKey="@filer.ConfigKey"
                                      @*asp-route-categoryname="@filer.categoryName"
                                      asp-route-pp="@filer.pp" *@
                                      asp-route-pagesize="@Model.Paging.ItemsPerPage"></cs-pager>
                        </div>
                        @*</div>*@
                    </div>
                }
            </div>
            <!-- END SAMPLE TABLE PORTLET-->
        </div>
    </div>
</section>

@section scripts{

    <script>

        $("#btn_add").click(function () {
            location.href = "/WebConfig/Create";
        });
    </script>

    <script>

        //删除
        function btndelete(id) {

            layer.confirm("确定删除", { title: "删除" }, function (index) {

                $.ajax({
                    url: "/WebConfig/Delete?id=" + id,
                    type: "POST",
                    cache: false,
                    success: function (r) {
                        if (r.code == 0) {
                            location.href = location.href;
                        }
                        else  // 其他问题
                        {
                            $.MsgBox.Alert(r.msg);
                        }
                    },
                    error: function () {

                        $.MsgBox.Alert("操作失败", "提示");
                    }
                });

                layer.close(index);
            });
        }
    </script>
}

src/03 Host/CompanyName.ProjectName.Web.Host/Views/WebConfig/edit.cshtml
@using  CompanyName.ProjectName.Web.Host.Model
@model CompanyName.ProjectName.ICommonServer.WebConfigDto
@{
    Layout = "_LayoutForm";
    ViewData["title"] = "配置编辑";
}

@section headers{

}

<form id="form1">

    @Html.HiddenFor(o => o.Id)

    @*@Html.HiddenFor(o => o.GoBackUrl)*@

    <div style="padding-top: 0px; margin-right: 30px;">
        <table class="form">
            <tr>
                <th class="formTitle"><span class="field-item-required light-red">*</span>key</th>
                <td class="formValue">
                    @Html.TextBoxFor(model => model.ConfigKey, new { placeholder = "请输入key", @class = "form-control" })
                </td>
                <td>
                    @Html.ValidationMessageFor(o => o.ConfigKey, null, new { @class = "help-inline" })
                </td>
            </tr>

            <tr>
                <th class="formTitle"><span class="field-item-required light-red">*</span>值</th>
                <td class="formValue">
                    @Html.TextBoxFor(model => model.ConfigValue, new { placeholder = "请输入值", @class = "form-control" })
                </td>
                <td>
                    @Html.ValidationMessageFor(o => o.ConfigValue, null, new { @class = "help-inline" })
                </td>
            </tr>

            <tr>
                <th class="formTitle"><span class="field-item-required light-red">*</span>环境</th>
                <td class="formValue">
                    @Html.TextBoxFor(model => model.ConfigType, new { placeholder = "请输入环境", @class = "form-control" })
                </td>
                <td>
                    @Html.ValidationMessageFor(o => o.ConfigType, null, new { @class = "help-inline" })
                </td>
            </tr>

            <tr>
                <th class="formTitle"><span class="field-item-required light-red">*</span>备注</th>
                <td class="formValue">
                    @Html.TextBoxFor(model => model.ConfigDetail, new { placeholder = "请输入备注", @class = "form-control" })
                </td>
                <td>
                    @Html.ValidationMessageFor(o => o.ConfigDetail, null, new { @class = "help-inline" })
                </td>
            </tr>
        </table>
        <div class="clearfix form-actions">
            <label class="col-sm-3 control-label" for="form-field-1"> &nbsp; </label>
            <div class="col-md-9">
                <button class="btn btn-info" type="button" id="btnSave">
                    <i class="ace-icon fa fa-check bigger-110"></i>
                    确定
                </button>
                &nbsp;
                &nbsp;
                &nbsp;
                &nbsp;
                <a href="/WebConfig/index" class="btn"><i class="ace-icon fa fa-arrow-left icon-on-left bigger-110"></i>返回</a>
            </div>
        </div>
    </div>
</form>

@section scripts{

    <script>
        // 提交操作
        $("#btnSave").click(function (ev) {
            var $form = $("#form1");
            ////ev.preventDefault();

            if ($form.valid()) {
                //  if (true) {
                //禁用提交按钮，避免重复提交
                $.ajax({
                    url: "/WebConfig/edit",
                    data: $form.serialize(),
                    type: "POST",
                    cache: false,
                    async: false,
                    beforeSend: function () {
                        $("#btnSave").attr("disabled", "disabled");
                    },
                    success: function (r) {

                        if (r.code == 0) {
                            location.href = "/WebConfig/index?ram=" + Math.random();// r.GoBackUrl;
                        }
                        else  // 其他问题
                        {
                            $.MsgBox.Alert(r.msg);
                        }
                        $("#btnSave").removeAttr("disabled");
                    },
                    error: function () {

                        $.MsgBox.Alert("保存失败");
                        $("#btnSave").removeAttr("disabled");
                    }
                });

            }
            else {
                //alert(5);
                //移除禁止按钮。
                $("#btnSave").removeAttr("disabled");

            }
        });
    </script>

}